language: go
sudo: false

go:
  - 1.16.x

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -u golang.org/x/tools/cmd/stringer
  - go get -u golang.org/x/lint/golint

script:
  - make test
  - go test -covermode=count -coverprofile=profile.cov ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -ignore=runtime/isa/opcode_string.go,data/function_string.go,read/token_string.go
